---
openapi: 3.0.4
info:
  title: Dave's Arcade API
  description: Game Catalog API showcasing Clean Architecture
  contact:
    name: David Hatzenbuehler
    url: https://github.com/DaveHatz23
  version: v1
paths:
  "/games":
    get:
      tags:
      - DavesArcade.Api
      responses:
        '200':
          description: OK
    post:
      tags:
      - DavesArcade.Api
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CreateGameRequest"
        required: true
      responses:
        '200':
          description: OK
  "/games/{id}":
    get:
      tags:
      - DavesArcade.Api
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: OK
    put:
      tags:
      - DavesArcade.Api
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UpdateGameRequest"
        required: true
      responses:
        '200':
          description: OK
    delete:
      tags:
      - DavesArcade.Api
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: OK
components:
  schemas:
    CreateGameRequest:
      type: object
      properties:
        name:
          type: string
          nullable: true
        genreId:
          type: string
          format: uuid
        price:
          type: number
          format: double
        releaseDate:
          type: string
          format: date
        description:
          type: string
          nullable: true
        imageUri:
          type: string
          nullable: true
        lastUpdatedBy:
          type: string
          nullable: true
      additionalProperties: false
    UpdateGameRequest:
      type: object
      properties:
        name:
          type: string
          nullable: true
        genreId:
          type: string
          format: uuid
        price:
          type: number
          format: double
        releaseDate:
          type: string
          format: date
        description:
          type: string
          nullable: true
      additionalProperties: false
tags:
- name: DavesArcade.Api
